---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: home-kubernetes
  sources:
    - repoURL: https://github.com/ajaykumar4/home-lab-argocd.git
      path: kubernetes/apps/kube-system/reloader
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/stakater/charts
      chart: reloader
      targetRevision: 1.0.115
      helm:
        releaseName: reloader
        valueFiles:
          - $repo/kubernetes/apps/kube-system/reloader/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
