---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: home-kubernetes
  sources:
    - repoURL: https://github.com/ajaykumar4/home-lab-argocd.git
      path: kubernetes/apps/network/ingress-nginx
      targetRevision: main
      ref: repo
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.10.1
      helm:
        releaseName: ingress-nginx-internal
        valueFiles:
          - $repo/kubernetes/apps/network/ingress-nginx/internal/values.sops.yaml
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.10.1
      helm:
        releaseName: ingress-nginx-external
        valueFiles:
          - $repo/kubernetes/apps/network/ingress-nginx/external/values.sops.yaml
  destination:
    name: in-cluster
    namespace: network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
