---
helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600
  recreatePods: true
  force: true

apiVersions:
  - monitoring.coreos.com/v1

releases:
  - name: argocd
    namespace: argocd
    chart: oci://ghcr.io/argoproj/argo-helm/argo-cd
    version: 7.3.4
    secrets:
      - secrets.sops.yaml
