---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: home-kubernetes
  sources:
    - repoURL: https://github.com/ajaykumar4/home-lab-argocd.git
      path: kubernetes/apps/cert-manager/cert-manager
      targetRevision: main
      ref: repo
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.15.1
      helm:
        releaseName: cert-manager
        valueFiles:
          - $repo/kubernetes/apps/cert-manager/cert-manager/values.yaml
    - repoURL: https://github.com/ajaykumar4/home-lab-argocd.git
      chart: kubernetes/apps/cert-manager/certificate-issuer
      targetRevision: main
      helm:
        releaseName: cert-manager
        valueFiles:
          - $repo/kubernetes/apps/cert-manager/certificate-issuer/values.sops.yaml
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
